// <auto-generated />
using System;
using DriversTestEvaluation.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriversTestEvaluation.Data.Migrations
{
    [DbContext(typeof(DriversTestEvaluationDbContext))]
    [Migration("20260609102632_AddedEntryFromSession")]
    partial class AddedEntryFromSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.Coordinates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("x")
                        .HasColumnType("float");

                    b.Property<double>("y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.DrivingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Penalty")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResultsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResultsId");

                    b.HasIndex("SessionId");

                    b.ToTable("DrivingEvent");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.DrivingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameWindowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<bool>("SessionActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DrivingSession");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorTrafficLight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InFrontOfTrafficLight")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("SpaceCarInFront")
                        .HasColumnType("float");

                    b.Property<double>("SpeedLimit")
                        .HasColumnType("float");

                    b.Property<double>("Speed_kmh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.Results", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfEvents")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.Coordinates", b =>
                {
                    b.HasOne("DriversTestEvaluation.Core.Models.DrivingSession", "Session")
                        .WithMany("Coordinates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.DrivingEvent", b =>
                {
                    b.HasOne("DriversTestEvaluation.Core.Models.Results", null)
                        .WithMany("Events")
                        .HasForeignKey("ResultsId");

                    b.HasOne("DriversTestEvaluation.Core.Models.DrivingSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.Entry", b =>
                {
                    b.HasOne("DriversTestEvaluation.Core.Models.DrivingSession", "Session")
                        .WithMany("Entries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.DrivingSession", b =>
                {
                    b.Navigation("Coordinates");

                    b.Navigation("Entries");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("DriversTestEvaluation.Core.Models.Results", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
